version: '3'
services:
  db:
    image: mysql:5.7
    ports:
    - "6603:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=654321
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=654321
    - MYSQL_DATABASE=mydb
    volumes:
    - ./src/db/init_db.sql:/docker-entrypoint-initdb.d/0init_db.sql
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: my-docker-image
    ports:
    - "8080:80"
    volumes:
    - ./src:/var/www/html
    depends_on:
    - db
  